# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bhier <- function(data, partitions, d_k) {
    .Call(`_fastbaps_bhier`, data, partitions, d_k)
}

compare_prior_grid <- function(data, grid) {
    .Call(`_fastbaps_compare_prior_grid`, data, grid)
}

import_fasta_to_vector_each_nt <- function(file) {
    .Call(`_fastbaps_import_fasta_to_vector_each_nt`, file)
}

part_llks <- function(data, partitions) {
    .Call(`_fastbaps_part_llks`, data, partitions)
}

