# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bhier <- function(data, partitions, d_k) {
    .Call('_fastbaps_bhier', PACKAGE = 'fastbaps', data, partitions, d_k)
}

bhier_parallel <- function(data, partitions, d_k, n_cores) {
    .Call('_fastbaps_bhier_parallel', PACKAGE = 'fastbaps', data, partitions, d_k, n_cores)
}

calc_ddk <- function(data, merges) {
    .Call('_fastbaps_calc_ddk', PACKAGE = 'fastbaps', data, merges)
}

import_fasta_to_vector_each_nt <- function(file) {
    .Call('_fastbaps_import_fasta_to_vector_each_nt', PACKAGE = 'fastbaps', file)
}

part_llks <- function(data, partitions) {
    .Call('_fastbaps_part_llks', PACKAGE = 'fastbaps', data, partitions)
}

start_profiler <- function(str) {
    .Call('_fastbaps_start_profiler', PACKAGE = 'fastbaps', str)
}

stop_profiler <- function() {
    .Call('_fastbaps_stop_profiler', PACKAGE = 'fastbaps')
}

tree_llk <- function(data, merges) {
    .Call('_fastbaps_tree_llk', PACKAGE = 'fastbaps', data, merges)
}

